Remove unnecessary controllers
futurewei-cloud/global-resource-scheduler pull request #16
Opened 2020-10-12 19:16 UTC by CoderKevinZhang

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2020-10-12 20:30 UTC, cathyhongzhang commented on cmd/kube-controller-manager/app/BUILD
> -        "//staging/src/k8s.io/client-go/scale:go_default_library",
Do you need to remove this scale related library? Could you double check that it is not needed for controller scaling?

2020-10-12 20:31 UTC, cathyhongzhang commented on cmd/kube-controller-manager/app/BUILD
>          "//pkg/volume/storageos:go_default_library",
It seems that you remove some volume related library but keep some. Could you clarify why?

2020-10-12 20:32 UTC, cathyhongzhang commented on cmd/kube-controller-manager/app/BUILD
>      ],
Why do you need to remove the policy.go and rbac.go? rbac.go seems to be related to role based access control.

2020-10-12 21:10 UTC, CoderKevinZhang commented on cmd/kube-controller-manager/app/BUILD
>      ],
policy.go is using disruption controller and rbac.go is using clusterroleaggregation controller. Neither of these two controllers is needed.

2020-10-12 21:25 UTC, CoderKevinZhang commented on cmd/kube-controller-manager/app/BUILD
>          "//pkg/volume/storageos:go_default_library",
these volume-related libraries are associated with persistentvolume-binder/attachdetach/persistentvolume-expander controllers

2020-10-12 22:02 UTC, CoderKevinZhang commented on cmd/kube-controller-manager/app/BUILD
> -        "//staging/src/k8s.io/client-go/scale:go_default_library",
the reason I remove client-go/scale is horizontalpodautoscaling controller is using it, and horizontalpodautoscaling controller is not needed

2020-10-12 22:03 UTC, CoderKevinZhang commented on cmd/kube-controller-manager/app/BUILD
> -        "//staging/src/k8s.io/client-go/scale:go_default_library",
Memo - we need to implement scaling in the future

2020-10-12 22:24 UTC, cathyhongzhang approved these changes

2020-10-13 02:03 UTC, cathyhongzhang requested changes
Need to add back the endpoint controller. I am sorry for asking you to make this change. Since leader election for HA in Kubernetes can use endpoint object, we'd better add back the endpoint controller.

2020-10-13 16:33 UTC, cathyhongzhang commented on test/e2e/network/service.go
>  	"k8s.io/kubernetes/test/e2e/framework"
Why is  this removed? Since endpoint controller is not removed, it seems we should not remove this.

2020-10-13 16:34 UTC, cathyhongzhang commented on test/e2e/network/BUILD
>          "//pkg/master/ports:go_default_library",
why is this removed? it seems that it does not need to be removed.

2020-10-13 18:13 UTC, CoderKevinZhang commented on test/e2e/network/service.go
>  	"k8s.io/kubernetes/test/e2e/framework"
I will add it back

2020-10-13 18:14 UTC, CoderKevinZhang commented on test/e2e/network/BUILD
>          "//pkg/master/ports:go_default_library",
I will add it back

2020-10-13 21:12 UTC, cathyhongzhang commented
LGTM

2020-10-13 21:12 UTC, cathyhongzhang approved these changes

2020-10-13 21:12 UTC, merged