Modify the pod spec by adding resource information
futurewei-cloud/global-resource-scheduler pull request #54
Opened 2020-10-23 19:00 UTC by jshaofuturewei

It is related to https://github.com/futurewei-cloud/global-resource-scheduler/issues/20

2020-10-27 18:48 UTC, CoderKevinZhang requested changes
I check your latest commit. Did you mixed your own change together with `make update`? We better separate them.

2020-10-30 18:01 UTC, jshaofuturewei commented
> I check your latest commit. Did you mixed your own change together with `make update`? We better separate them.

I have divided the request into 3 commits.

2020-10-30 19:21 UTC, CoderKevinZhang commented on pkg/kubelet/container/helpers_test.go
> +	v1 "k8s.io/api/core/v1"
Do you need to add another v1 before "k8s.io/api/core/v1"? I think there is no difference

2020-10-30 19:21 UTC, CoderKevinZhang commented on pkg/kubelet/container/helpers_test.go
> +			0x8f232301,
Just curious, did you change it yourself? How did you know what value you should change

2020-10-30 20:25 UTC, jshaofuturewei commented on pkg/kubelet/container/helpers_test.go
> +	v1 "k8s.io/api/core/v1"
Other packages might have v1 version. Add this to clarify.

2020-10-30 20:26 UTC, jshaofuturewei commented on pkg/kubelet/container/helpers_test.go
> +			0x8f232301,
Yes, just tracking its address.

2020-10-30 20:27 UTC, CoderKevinZhang approved these changes

2020-10-30 20:29 UTC, kimeunju108 approved these changes
LGTM

2020-10-30 20:35 UTC, merged