Add scheduler API/controller - no logical implementation
futurewei-cloud/global-resource-scheduler pull request #72
Opened 2020-11-03 23:40 UTC by CoderKevinZhang

**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2020-11-04 20:39 UTC, kimeunju108 requested changes

2020-11-04 20:39 UTC, kimeunju108 commented on globalscheduler/controllers/scheduler/scheduler_controller.go
> +	sc.enqueueScheduler(obj)
I am wondering if you don't need to use "KeyWithEventType" which is recommended to use in arktos controllers.

2020-11-04 20:41 UTC, kimeunju108 requested changes
scheduler function not working

2020-11-04 20:45 UTC, CoderKevinZhang commented on globalscheduler/controllers/scheduler/scheduler_controller.go
> +	sc.enqueueScheduler(obj)
Let me do the research on how arktos controllers did it

2020-11-09 19:11 UTC, CoderKevinZhang commented on globalscheduler/controllers/scheduler/scheduler_controller.go
> +	sc.enqueueScheduler(obj)
I have already added event type in my controller, thanks.

2020-11-09 20:00 UTC, kimeunju108 approved these changes
LGTM

2020-11-09 20:03 UTC, jshaofuturewei approved these changes
Can you squash your commits?  There are too many of them

2020-11-09 22:57 UTC, merged